# Generated by Django 6.0.2 on 2026-02-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MapView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(help_text='1 = default full view, 2+ = detail/variation views')),
                ('filename', models.CharField(help_text='Base filename for tiles, e.g. 1700_3_1798', max_length=200)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('interpretive_text', models.TextField(blank=True, help_text='HTML subset: p, em, strong, ul, li')),
                ('is_crop', models.BooleanField(default=False, help_text='Whether this view shows a cropped detail')),
                ('crop_x', models.IntegerField(blank=True, null=True)),
                ('crop_y', models.IntegerField(blank=True, null=True)),
                ('crop_width', models.IntegerField(blank=True, null=True)),
                ('crop_height', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, help_text='Full image width in pixels (from .dzi file)', null=True)),
                ('image_height', models.IntegerField(blank=True, help_text='Full image height in pixels (from .dzi file)', null=True)),
                ('mapset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='maps.mapset')),
            ],
            options={
                'ordering': ['mapset', 'ordinal'],
                'unique_together': {('mapset', 'ordinal')},
            },
        ),
    ]
