# Generated by Django 6.0.2 on 2026-03-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapset',
            name='aspect_ratio',
            field=models.CharField(default='3/5', help_text='CSS aspect-ratio value, e.g. "3/5" or "4/3"', max_length=20),
        ),
        migrations.AddField(
            model_name='mapset',
            name='map_orientation',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', help_text='Portrait layout: vertical maps set height; horizontal maps fill width', max_length=20),
        ),
    ]
