# Generated by Django 6.0.2 on 2026-03-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_add_orientation_and_aspect_ratio_to_mapset'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapset',
            name='date',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='mapset',
            name='short_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mapview',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
