# Generated by Django 6.0.2 on 2026-03-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_mapset_date_mapset_short_title_mapview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapview',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
