# Generated by Django 6.0.2 on 2026-04-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_mapview_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapset',
            options={'ordering': ['slug']},
        ),
        migrations.AddField(
            model_name='mapset',
            name='credit',
            field=models.TextField(blank=True, help_text='HTML credit/attribution text (Summernote)'),
        ),
    ]
