# Generated by Django 6.0.2 on 2026-04-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_mapset_options_mapset_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapset',
            name='credit',
            field=models.TextField(blank=True, help_text='shift + enter for plain line return'),
        ),
        migrations.AlterField(
            model_name='mapview',
            name='ordinal',
            field=models.PositiveIntegerField(help_text='1 = default full view, 2+ = detail/variation views', verbose_name='View Number'),
        ),
    ]
